### ISSUE TITLE
Write an install script

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#264]
Pyinstaller can build either a single-file or a single-directory frozen app. The single-file package is better for users (since they don't have to search for the actual executable to run within a long list of other files), but the disadvantage is Pyinstaller must unpack the contents of the single-file executable into a temporary directory every time it is invoked. This has the effect of slowing down invocation (considerably if the app is large).

A workaround to this would be to always prefer the single-directory frozen app, but to provide an additional install script that users can run, which would add the executable to somewhere on PATH.

The install script could approximately mimic [Poetry's install script](https://install.python-poetry.org//), which does something similar. The main functionality of Poetry's install script is [discussed here](https://python-poetry.org/docs/).

We would also need to package up this install script using Pyinstaller, since we mustn't be dependent on Python being available.

**Comment by aplowman** [comment]
@cjfullerton Actually, maybe you are right; we could just use shell scripts for now. We can always switch to Python later if we need to.

**Comment by cjfullerton** [comment]
Will start by adding build of pyinstaller "one directory" to current relevant GHA workflows.

**Comment by cjfullerton** [comment]
Now building one folder version for hpcflow-new. Executable goes in `pyinstaller/dist/onefile` and folder in `pyinstaller/dist/onefolder`.

Now update `python-release-workflow` to upload onefolder output and reflect location changes of executable.

**Comment by cjfullerton** [comment]
- [ ] Upload onefolder version
- [ ] Run tests onefolder version
- [ ] Download onefolder
- [ ] Place onefolder (look at platformdirs)
- [ ] Make onefolder executable findable by user

**Comment by cjfullerton** [comment]
@aplowman Windows and linux onefolder versions are here if you want to try one: https://github.com/cjfullerton/hpcflow-new/actions/runs/3418704318

It looks like getting the macOS version past security might be a problem due to compiled files calling each other. I might need to manually 'certify' each one. Hopefully I can find a workaround.

**Comment by aplowman** [comment]
I think the one-dir artefacts are overwriting the one-file artefacts --- they have the same upload name; for example, [here](https://github.com/cjfullerton/hpcflow-new/actions/runs/3418704318/workflow#L92).

Perhaps we append `-dir` to the one-dir outputs (and in the case of windows, omit the .exe extension)?

**Comment by cjfullerton** [comment]
Aye, I'm hoping someone has encountered this before.

re: folder names - yes, had spotted that and will fix. Windows folder version is actually missing exe already, but upload command is still pointing to the one file version.

**Comment by cjfullerton** [comment]
Separate issue for macOS signing: https://github.com/hpcflow/python-release-workflow/issues/10

**Comment by cjfullerton** [comment]
Build and upload in build-exes now working. See: https://github.com/cjfullerton/hpcflow-new/actions/runs/3436506002

Next- add test suite execution for onefolder versions to check compiled outputs are functional.

**Comment by cjfullerton** [comment]
Making a note here: I think build-exes and release should fail if artefact upload step fails. Currently only a warning is given, and the workflow fails downstream.

**Comment by cjfullerton** [comment]
Determining OS from script:

- [Bash](https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script)
- [Powershell](https://stackoverflow.com/questions/44703646/determine-the-os-version-linux-and-windows-from-powershell)

**Comment by cjfullerton** [comment]
Use platformdirs for directory suggestions for each OS: https://github.com/platformdirs/platformdirs

**Comment by cjfullerton** [comment]
Download links have regular structure. Can construct link knowing version number and OS name.

**Comment by cjfullerton** [comment]
from platformdirs:
- macOS: `~/Library/Application Support/$appname/$version`
- linux: `~/.local/share/$appname/$version` or `$XDG_DATA_HOME/$appname/$version`
- windows: ` %USERPROFILE%\AppData\Local\$appauthor\$appname` (not roaming) or `%USERPROFILE%\AppData\Roaming\$appauthor\$appname` (roaming)

**Comment by cjfullerton** [comment]
Note that release action is actually compressing dist/onedir/hpcflow-$VERSION-$OSNAME-dir.zip, so extracting restores this structure.

Zip only hpcflow-$VERSION-$OSNAME-dir.zip for more consistent behaviour.

**Comment by cjfullerton** [comment]
Repo containing basic bash script created: https://github.com/hpcflow/install-folder-version

Script downloads and extracts the latest OS specific version.

Get commitizen to update latest version in install data file?

**Comment by cjfullerton** [comment]
Confirm that the command:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/hpcflow/install-folder-version/main/test-install-complete.sh)"`

works with macOS (zsh) at least.

**Comment by cjfullerton** [comment]
It would be nice to make the script look nice by (e.g.) suppressing curl and zip output, using fancy colours and adding things like progress bars (https://www.baeldung.com/linux/command-line-progress-bar).

**Comment by cjfullerton** [comment]
Curl and unzip now run in silent/quiet mode.

**Comment by cjfullerton** [comment]
mkdir and mv behaving oddly when given filepaths stored in variable - I suspect I'm missing something obvious.

**Comment by cjfullerton** [comment]
Most permissions seem to be okay on download (i.e. `rwx` for relevant files). Contents of `hpcflow-version-os-dir/tk/` are read only. Script sets them to `rw` to make deletion easier.

**Comment by cjfullerton** [comment]
Testing methods of having names command line arguments for bash scripts: https://brianchildress.co/named-parameters-in-bash/

**Comment by cjfullerton** [comment]
Added command line options to set installed version and folder installed to. Next: improve "add to path" message on finish.

**Comment by cjfullerton** [comment]
Basic powershell script added - need to test in proper windows environment.

**Comment by cjfullerton** [comment]
Mini to-do:

- [ ] Download to temp directory
- [ ] Create symlink to latest version, keep all versions in path
- [ ] How to execute ps1 scripts?
- [ ] Add update version of script
- [ ] Add option to download one executable version

**Comment by cjfullerton** [comment]
Bash version now uses temp directory for download and decompression and creates a symlink to the just installed version.

**Comment by cjfullerton** [comment]
See this project board for more detailed info: https://github.com/orgs/hpcflow/projects/7/views/3
