### ISSUE TITLE
[FUTURE] Remove support for Python 3.7

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#313]
Python 3.7 [support ends around June 2023](https://peps.python.org/pep-0537). After this time, we should no longer test against it, and should bump the minimum support version in the pyproject.toml file to Python 3.8.

This issue could also serve as a note of Python 3.8 features that we can then use.

**Comment by aplowman** [comment]
Features we can use in Python 3.8 that are not in Python 3.7:

- f-strings like this: `f"{var_name=}"`

**Comment by aplowman** [comment]
Features in Python 3.10:
- Dataclass `slots=True` for smaller class objects: https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass
- Typing "Union type; Union[X, Y] is equivalent to X | Y and means either X or Y" https://docs.python.org/3/library/typing.html#typing.Union

**Comment by cjfullerton** [comment]
This is in update-CentOS branch - waiting on 3.11 status.

**Comment by cjfullerton** [comment]
Closing as complete.
