### ISSUE TITLE
Automate issue addition to project board backlog (at least) and transition between statuses

### ISSUE THREAD

**Issue by cjfullerton** [hpcflow/hpcflow-new#360]

**Comment by cjfullerton** [comment]
I've turned some of these on:

- New issues in hpcflow-new should get added to the board.
- New board items should be added to to-do automatically.
- Closed issues should be moved to done.

Some things that don't work yet:

- Issues in the other project repos don't get added automatically
- Since main is our default branch, merging a PR into develop doesn't close issues. We still need to move issues associated with these pull requests into the 'awaiting merge' column.

**Comment by cjfullerton** [comment]
We can in theory duplicate the auto-add workflow to add issues from our other repos to the board, but it's a paid for feature.

Will just need to check the issues periodically to make sure we haven't missed any.

I'll close for now.

**Comment by cjfullerton** [comment]
Re-opening - looks like we can solve issue addition with a custom github action.

Might be able to auto-move issues to 'awaiting merge' column using this as well.

**Comment by cjfullerton** [comment]
Added action to hpcflow/python-release-workflow to test. Need to sort out key so it can add issues to the board.

**Comment by cjfullerton** [comment]
Have added this actions workflow to:
- hpcflow/hpcflow-new
- hpcflow/matflow-new
- hpcflow/python-release-workflow
- hpcflow/install-folder-version
- hpcflow/docs.matflow.io
- hpcflow/hpcflow.github.io

Any others @aplowman , @fherreazcue ?

**Comment by fherreazcue** [comment]
potentially the container one: docker-centos7-poetry

**Comment by aplowman** [comment]
also hpcflow/valida

**Comment by cjfullerton** [comment]
Done. I'll close this now.

Have made a separate issue for custom change of issue status.
