### ISSUE TITLE
Write a contributing guide

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#362]
We should decide on and write down our contributing guidance.

E.g. when making a PR, should we ask that the target branch is rebased onto the PR branch? I've been merging so far, but merge commits don't really fit into the conventional commits convention.

**Comment by cjfullerton** [comment]
Let's aim for something bare bones at a minimum.

**Comment by cjfullerton** [comment]
@fherreazcue has written some notes - use this as a basis?

**Comment by fherreazcue** [comment]
See initial notes [here](https://github.com/hpcflow/hpcflow-new/commit/8fd9d8ee487373671cacb710327f6e3c85527ca4).

**Comment by aplowman** [comment]
The initial notes are merged, but more work will be needed.
