### ISSUE TITLE
Add action to move issues to 'awaiting merge'

### ISSUE THREAD

**Issue by cjfullerton** [hpcflow/hpcflow-new#370]
Add action to automatically move issues to 'awaiting merge' column if the pull request they are associated with is merged into develop branch.

Amended: we're considering these issues 'done' and closed. 'awaiting merge' status if for issues that are closed by a PR that hasn't been merged into main or develop.

Action should move issues to 'done' when the PR they are linked to is merged. Additonally could close them?

**Comment by fherreazcue** [comment]
Should this move them to "done" instead?

**Comment by cjfullerton** [comment]
Yes, it should. Will amend now.
