### ISSUE TITLE
Get copy functionality working on code blocks on install page of documentation

### ISSUE THREAD

**Issue by cjfullerton** [hpcflow/hpcflow-new#379]
Code blocks appear, but copy functionality doesn't appear to be working.

Fix this.

**Comment by aplowman** [comment]
Do you mean the `pip install` block? Seems to work for me in Edge.

**Comment by cjfullerton** [comment]
No, it's for the install script blocks. The hpcflow version hasn't built yet, but they aren't there on the matflow docs (https://docs.matflow.io/stable/install/index.html).

I must have missed something.
