### ISSUE TITLE
Allow specifying default scheduler/options to the config file

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow-new#443]
This could be a mapping between scheduler names (SGE, Slurm, None/direct) and default options. And we should also indicate which should be the default scheduler type.

A related problem cropped up at the recent user meeting: when adding elements locally to a workflow that has previously executed on a cluster, the new elements will inherit the workflow's default resources, which in this case used a scheduler, which is not what we want to use for local execution.

**Comment by cjfullerton** [comment]
Needs checking.

**Comment by aplowman** [comment]
Fixed
